### ISSUE TITLE
Email formatting headings and carriage returns

### ISSUE THREAD

**Issue by twitchy53** [mlooft/multi-step-form#8]
Love the plug in, on the email that is received, the headings aren't spanning multiple colums, so they are only as wide as the first column.  Also, any textarea input field isn't translating carriage returns.  I've looked at the file and it's a bit beyond me unfortunately.

**Comment by NHollmann** [comment]
As of version 1.3.1 textareas keep the newlines the user entered in the email.
The column span of the headings is indeed unwanted and should be fixed in the next version.
